//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using Livesplit.CS3;
using LiveSplit.UI.Components;

[assembly: System.Reflection.AssemblyCompanyAttribute("Livesplit.CS3")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("Livesplit.CS3")]
[assembly: System.Reflection.AssemblyTitleAttribute("Livesplit.CS3")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: ComponentFactory(typeof(CS3Factory))]

// Generated by the MSBuild WriteCodeFragment class.

